# Generated by Django 2.2.6 on 2019-12-21 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietBooking',
            fields=[
                ('mabooking', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ngaynhanphong', models.DateTimeField(default=django.utils.timezone.now)),
                ('ngaytratphong', models.DateTimeField(default=django.utils.timezone.now)),
                ('thanhtien', models.BigIntegerField(default=0)),
                ('tendn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
