# Generated by Django 2.2.6 on 2019-12-21 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phong', '0001_initial'),
        ('chitietbooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietbooking',
            name='sophong',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='phong.Phong'),
        ),
    ]
