# Generated by Django 2.2.6 on 2019-12-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chitietbooking', '0002_chitietbooking_sophong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietbooking',
            name='mabooking',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
