# Generated by Django 2.2.6 on 2019-12-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('sophong', models.CharField(default=0, max_length=30, primary_key=True, serialize=False)),
                ('loaiphong', models.IntegerField(choices=[(0, 'Phòng cao cấp Loại 1'), (2, 'Phòng đôi'), (3, 'Phòng trẻ em'), (1, 'Phòng đơn')], default=0)),
                ('gia', models.BigIntegerField(default=0)),
            ],
        ),
    ]
