# Generated by Django 2.2.6 on 2019-12-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phong', '0003_auto_20191224_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='loaiphong',
            field=models.IntegerField(choices=[(2, 'Phòng đôi'), (0, 'Phòng cao cấp Loại 1'), (1, 'Phòng đơn'), (3, 'Phòng trẻ em')], default=0),
        ),
    ]
