# Generated by Django 2.2.6 on 2019-12-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phong', '0005_auto_20191225_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phong',
            name='loaiphong',
            field=models.IntegerField(choices=[(2, 'Deluxe Room'), (1, 'Superior Room'), (4, 'Executive Suite Room'), (6, 'Adjacent Rooms'), (3, 'Suite Room'), (7, 'Hollywood Twin Room'), (5, 'President Suite Room'), (0, 'Standard Room')], default=0),
        ),
    ]
